package com.softpos.pos.core.model;

import java.util.Date;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
public class BalanceBean {

    private String R_Index = "0";
    private String R_Table;
    private Date R_Date;
    private String R_Time;
    private String R_LoginDate;
    private String LoginTime;
    private String Macno;
    private String Cashier;
    private String R_Emp;
    private String R_PluCode;
    private String R_PName;
    private String R_Unit;
    private String R_Group;
    private String R_Status;
    private String R_Normal;
    private String R_Discount;
    private String R_Service;
    private String R_Stock;
    private String R_Set;
    private String R_Vat;
    private String R_Type;
    private String R_ETD;
    private double R_Quan = 0.000;
    private double R_Price = 0.00;
    private double R_Total = 0.00;
    private String R_PrType;
    private String R_PrCode;
    private double R_PrDisc;
    private double R_PrBath = 0.00;
    private double R_PrAmt = 0.00;
    private double R_DiscBath = 0.000000;
    private String R_PrCuType;
    private double R_PrCuQuan = 0;
    private double R_PrCuAmt = 0.00;
    private double R_Redule = 0.00;
    private String R_Kic;
    private String R_KicPrint;
    private String R_Void;
    private String R_VoidUser;
    private String R_VoidTime;
    private String R_MenuSet1;
    private String R_MenuSet2;
    private String R_MenuSet3;
    private String R_MenuSet4;
    private String R_MenuSet5;
    private String R_MenuSet6;
    private String R_MenuSet7;
    private String R_MenuSet8;
    private String R_MenuSet9;
    private String R_MenuSet10;
    private String R_MenuSet11;
    private String R_MenuSet12;
    private String R_MenuSet13;
    private String R_MenuSet14;
    private String R_MenuSet15;
    private String R_Opt1;
    private String R_Opt2;
    private String R_Opt3;
    private String R_Opt4;
    private String R_Opt5;
    private String R_Opt6;
    private String R_Opt7;
    private String R_Opt8;
    private String R_Opt9;
    private String R_PrCuCode;
    private String R_Serve = "N";
    private String R_PrintOK = "N";
    private String R_KicOK = "N";
    private String StkCode;
    private String PosStk = "Y";
    private String R_PrChkType;
    private double R_PrQuan;
    private String R_PrSubType;
    private String R_PrSubCode;
    private double R_PrSubQuan;
    private double R_PrSubDisc;
    private double R_PrSubBath;
    private double R_PrSubAmt;
    private double R_PrSubAdj;
    private double R_PrCuDisc;
    private double R_PrCuBath;
    private double R_PrCuAdj;
    private double R_QuanCanDisc;
    private String R_Order = "0";
    private int R_PItemNo = 0;
    private int R_PKicQue = 0;
    private String R_MemSum = "N";
    private String R_MoveItem = "N";
    private String R_MoveFrom;
    private String R_MoveUser;
    private String R_MoveFlag = "0";
    private String R_MovePrint = "N";
    private String R_Pause;
    private String R_CardPay = "N";
    private String R_Pickup = "P";
    private String R_CallWait;
    private String R_LinkIndex;
    private String R_VoidPause;
    private String R_SPIndex;
    private String R_CashCard;
    private String VoidMSG = "";
    private String R_PEName;
    private double R_ServiceAmt;
    private String R_Indulgent;
}
