package com.softpos.pos.core.model;

import java.util.Date;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
public class BranchBean {

    private String Code = "XXX";
    private String Name = "New Branch";
    private String AddressNo;
    private String Locality;
    private String SubProvince;
    private String Province;
    private String Post;
    private String Tel_No;
    private String Fax_No;
    private String E_Mail;
    private String Manager;
    private String Location_Area;
    private double Ser_Area = 0.00;
    private double Cou_Area = 0.00;
    private double Kic_Area = 0.00;
    private double Tot_Area = 0.00;
    private double Cost = 0.00;
    private double Charge = 0.00;
    private String FlageCost = "N";
    private double Gp = 0.00;
    private String FlageGp = "N";
    private String Remark;
    private double ArBillNo = 1;
    private double EarneatBillNo = 1;
    private double ReturnBillNo = 1;
    private Date PrintAutoSumDate;
    private String SaveOrder = "N";
    private String SaveOrderCopy = "N";
    private String SaveOrderChk = "N";
    private String KIC1 = "N";
    private String KIC2 = "N";
    private String KIC3 = "N";
    private String KIC4 = "N";
    private String KIC5 = "N";
    private String KIC6 = "N";
    private String KIC7 = "N";
    private String KIC8 = "N";
    private String KIC9 = "N";
    private String SmartCard = "N";
    private String GetFile;
    private String RetFile;
    private String PointFile;
    private int CntLoop = 1;
    private double InvNo = 1;
    private double InvCashNo = 1;
    private double InvCash = 1;
    private String InvActive = "Y";
    private String CreditAct;
    private String PromotionGP;
    private int LockTime = 0;
    private int KicItemNo = 0;
    private String PT1;
    private String PT2;
    private String PT3;
    private String PT4;
    private String PT5;
    private int PONO = 1;
    private String PrintKicForm = "1";
    private String PrintInvForm = "1";
    private String PSelectStk = "P";
    private String PStkChk = "N";
    private String PMinStkChk = "N";
    private double RoundUpTime = 0;
    private String GiftStatusChk = "N";
    private String KICCopy1 = "6";
    private String KICCopy2 = "6";
    private String KICCopy3 = "6";
    private String KICCopy4 = "6";
    private String KICCopy5 = "6";
    private String KICCopy6 = "6";
    private String KICCopy7 = "6";
    private String KICCopy8 = "6";
    private String KICCopy9 = "6";
    private String KICChk1 = "N";
    private String KICChk2 = "N";
    private String KICChk3 = "N";
    private String KICChk4 = "N";
    private String KICChk5 = "N";
    private String KICChk6 = "N";
    private String KICChk7 = "N";
    private String KICChk8 = "N";
    private String KICChk9 = "N";
    private String UpdateBranchPoint = "Y";
    private String KicName1;
    private String KicName2;
    private String KicName3;
    private String KicName4;
    private String KicName5;
    private String KicName6;
    private String KicName7;
    private String KicName8;
    private String KicName9;
    private String KicPrintOnReceipt1 = "N";
    private String KicPrintOnReceipt2 = "N";
    private String KicPrintOnReceipt3 = "N";
    private String KicPrintOnReceipt4 = "N";
    private String KicPrintOnReceipt5 = "N";
    private String KicPrintOnReceipt6 = "N";
    private String KicPrintOnReceipt7 = "N";
    private String KicPrintOnReceipt8 = "N";
    private String KicPrintOnReceipt9 = "N";
    private int KicQue = 0;
    private String Kic10 = "N";
    private String Kic11 = "N";
    private String Kic12 = "N";
    private String Kic13 = "N";
    private String Kic14 = "N";
    private String Kic15 = "N";
    private String Kic16 = "N";
    private String Kic17 = "N";
    private String Kic18 = "N";
    private String Kic19 = "N";
    private String Kic20 = "N";
    private String KicCopy10 = "1";
    private String KicCopy11 = "1";
    private String KicCopy12 = "1";
    private String KicCopy13 = "1";
    private String KicCopy14 = "1";
    private String KicCopy15 = "1";
    private String KicCopy16 = "1";
    private String KicCopy17 = "1";
    private String KicCopy18 = "1";
    private String KicCopy19 = "1";
    private String KicCopy20 = "1";
    private String KicChk10 = "N";
    private String KicChk11 = "N";
    private String KicChk12 = "N";
    private String KicChk13 = "N";
    private String KicChk14 = "N";
    private String KicChk15 = "N";
    private String KicChk16 = "N";
    private String KicChk17 = "N";
    private String KicChk18 = "N";
    private String KicChk19 = "N";
    private String KicChk20 = "N";
    private String imageHomePath = "";

}
