package com.softpos.pos.core.model;

import java.util.Date;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
public class ProtabBean {

    private String ProCode;
    private String Prodesc;
    private Date PDate1;
    private Date PDate2;
    private String PStrDay;
    private String PTime1S = "00:00";
    private String PTime1E = "00:00";
    private int PDisc1 = 0;
    private double PSPDisc1 = 0.00;
    private String PTS1;
    private String PTime2S = "00:00";
    private String PTime2E = "00:00";
    private int PDisc2 = 0;
    private double PSPDisc2 = 0.00;
    private String PTS2;
    private String PTime3S = "00:00";
    private String PTime3E = "00:00";
    private int PDisc3 = 0;
    private double PSPDisc3 = 0.00;
    private String PTS3;
    private String PType = "1";
    private int PSale1 = 0;
    private int PFree1 = 0;
    private int PSum1 = 0;
    private double PDiscFree1 = 0.00;
    private int PSale2 = 0;
    private int PFree2 = 0;
    private int PSum2 = 0;
    private double PDiscFree2 = 0.00;
    private int PSale3 = 0;
    private int PFree3 = 0;
    private int PSum3 = 0;
    private double PDiscFree3 = 0.00;
    private int PSale41 = 0;
    private int PFree41 = 0;
    private int PSale42 = 0;
    private int PFree42 = 0;
    private int PSale43 = 0;
    private int PFree43 = 0;
    private double PQty11 = 0;
    private double PQty12 = 0;
    private double PQty13 = 0;
    private double PQty14 = 0;
    private double PQDisc11 = 0.00;
    private double PQDisc12 = 0.00;
    private double PQDisc13 = 0.00;
    private double PQDisc14 = 0.00;
    private double PQBath11 = 0.00;
    private double PQBath12 = 0.00;
    private double PQBath13 = 0.00;
    private double PQBath14 = 0.00;
    private double PQty21 = 0;
    private double PQty22 = 0;
    private double PQty23 = 0.00;
    private double PQty24 = 0;
    private double PQDisc21 = 0.00;
    private double PQDisc22 = 0.00;
    private double PQDisc23 = 0.00;
    private double PQDisc24 = 0.00;
    private double PQBath21 = 0.00;
    private double PQBath22 = 0.00;
    private double PQBath23 = 0.00;
    private double PQBath24 = 0.00;
    private double PQty31 = 0;
    private double PQty32 = 0;
    private double PQty33 = 0;
    private double PQty34 = 0;
    private double PQDisc31 = 0.00;
    private double PQDisc32 = 0.00;
    private double PQDisc33 = 0.00;
    private double PQDisc34 = 0.00;
    private double PQBath31 = 0.00;
    private double PQBath32 = 0.00;
    private double PQBath33 = 0.00;
    private double PQBath34 = 0.00;
    private String P6SaleCode1;
    private String P6SaleCode2;
    private String P6SaleCode3;
}
