package com.softpos.pos.core.model;

import java.util.Date;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
public class TSaleBean {
    private String R_Index = "0";
    private String R_Refno;
    private String R_Table;
    private Date R_Date;
    private String R_Time;
    private String MacNo;
    private String Cashier;
    private String R_Emp;
    private String R_PluCode;
    private String R_PName;
    private String R_Unit;
    private String R_Group;
    private String R_Status;
    private String R_Normal;
    private String R_Discount;
    private String R_Service;
    private String R_Stock;
    private String R_Set;
    private String R_Vat;
    private String R_Type;
    private String R_ETD;
    private double R_Quan;
    private double R_Price;
    private double R_Total;
    private String R_PrType;
    private String R_PrCode;
    private double R_PrDisc;
    private double R_PrBath;
    private double R_PrAmt;
    private String R_PrCuType;
    private String R_PrCuCode;
    private double R_PrCuQuan;
    private double R_PrCuAmt;
    private double R_Redule = 0.00;
    private double R_DiscBath;
    private double R_PrAdj;
    private double R_PreDisAmt = 0.00;
    private double R_NetTotal;
    private String R_Kic;
    private String R_KicPrint;
    private String R_Refund = "-";
    private String VoidMsg;
    private String R_Void = "-";
    private String R_VoidUser;
    private String R_VoidTime;
    private String StkCode;
    private String PosStk = "Y";
    private double R_ServiceAmt = 0.00;
    private String R_PrChkType;
    private double R_PrQuan;
    private String R_PrSubType;
    private String R_PrSubCode;
    private double R_PrSubQuan;
    private double R_PrSubDisc;
    private double R_PrSubBath;
    private double R_PrSubAmt;
    private double R_PrSubAdj;
    private double R_PrCuDisc;
    private double R_PrCuBath;
    private double R_PrCuAdj;
    private String R_PrChkType2;
    private double R_PrQuan2;
    private String R_PrType2;
    private String R_PrCode2;
    private double R_PrDisc2;
    private double R_PrBath2;
    private double R_PrAmt2;
    private double R_PrAdj2;
    private int R_PItemNo = 0;
    private int R_PKicQue = 0;
    private String R_MoveItem = "N";
    private String R_MoveFrom = "0";
    private String R_MoveUser = "0";
    private String R_MoveFlag = "0";
    private String Bill_macno;
    private String R_CardPay = "N";
    private String R_LinkIndex;
    private String R_Pause;
    private String R_VoidPause;
    private String R_SPIndex;
    private double R_CashCard = 0.000000;
    private String R_Opt1;
    private String R_Opt2;
    private String R_Opt3;
    private String R_Opt4;
    private String R_Opt5;
    private String R_Opt6;
    private String R_Opt7;
    private String R_Opt8;
    private String R_Opt9;
    private double R_NetDiff = 0.00;
    private String R_SendOnline = "";
    private String R_BranchCode = "";

    private String R_PrVcType = "";
    private String R_PrVcCode = "";
    private double R_PrVcAmt = 0.00;
    private double R_PrVcAdj = 0.00;

    private double R_SetPrice = 0.00;
    private double R_SetDiscAmt = 0.00;
    private String R_PrintItemBill = "";
    private String R_CountTime = "";
    private String R_Return = "";
    private String R_Earn = "";
    private String R_EarnNo = "";
}
