package com.softpos.posreport;

import com.softpos.pos.core.model.POSHWSetup;
import com.softpos.printer.control.PPrint;
import com.softpos.pos.core.controller.PUtility;
import com.softpos.constants.PublicVar;

import com.softpos.pos.core.controller.MemmaterController;
import com.softpos.connection.database.MySQLConnect;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import com.softpos.printer.control.PrinterDriverControl;
import com.softpos.util.AppLogUtil;
import com.softpos.util.DateConvert;
import com.softpos.util.MSG;

public class ArPaymentReport extends javax.swing.JDialog {

    SimpleDateFormat DatefmtThai = new SimpleDateFormat("dd/MM/yyyy(HH:mm)", Locale.ENGLISH);
    SimpleDateFormat ShowDatefmt = new SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH);
    DecimalFormat DecFmt = new DecimalFormat("##,###,##0.00");
    DecimalFormat IntFmt = new DecimalFormat("##,###,##0");
    Date date = new Date();
    PPrint prn = new PPrint();
    private final POSHWSetup POSHW;
    private final String Space = " &nbsp; ";
    private final String TAB = Space + Space + Space;
    private final MySQLConnect mysqlConnect = new MySQLConnect();
    private final POSHWSetup POSHWSetup = new POSHWSetup();
    private final PUtility PUtility = new PUtility();
    

    /**
     * Creates new form ArPaymentRep
     */
    public ArPaymentReport(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtMacNo1.setText("001");
        txtMacNo2.setText("001");

        POSHW = POSHWSetup.Bean(PublicVar.MACNO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bntOK = new javax.swing.JButton();
        bntExit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMacNo1 = new javax.swing.JTextField();
        txtMacNo2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("รายงานการรับชำระจากลูกหนี้ภายนอก (AR Payment Report)");
        setUndecorated(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bntOK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntOK.setText("พิมพ์");
        bntOK.setFocusable(false);
        bntOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntOKActionPerformed(evt);
            }
        });

        bntExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntExit.setText("ยกเลิก");
        bntExit.setFocusable(false);
        bntExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExitActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray, 3));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("หมายเลขเครื่อง");

        txtMacNo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMacNo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMacNo1KeyPressed(evt);
            }
        });

        txtMacNo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMacNo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMacNo2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtMacNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMacNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMacNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMacNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bntExit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntOK, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntOK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void txtMacNo1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMacNo1KeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
        bntExitClick();
    }
    if (evt.getKeyCode() == KeyEvent.VK_F5) {
        bntOKClick();
    }
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

        txtMacNo2.requestFocus();

    }
}//GEN-LAST:event_txtMacNo1KeyPressed

private void txtMacNo2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMacNo2KeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
        bntExitClick();
    }
    if (evt.getKeyCode() == KeyEvent.VK_F5) {
        bntOKClick();
    }
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        txtMacNo1.requestFocus();
    }
}//GEN-LAST:event_txtMacNo2KeyPressed

private void bntOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntOKActionPerformed
    bntOKClick();
}//GEN-LAST:event_bntOKActionPerformed

private void bntExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExitActionPerformed
    bntExitClick();
}//GEN-LAST:event_bntExitActionPerformed

    public void bntOKClick() {
        String MacNo1 = txtMacNo1.getText();
        String MacNo2 = txtMacNo2.getText();
        if (PublicVar.useprint) {
            if (PublicVar.printdriver) {
                arPaymentPrintDriver(MacNo1, MacNo2);
            } else if (!POSHW.getPRNPort().equals("NONE")) {
                if (prn.openPrint(POSHW.getPRNPort())) {
                    Double SumAmt = 0.0;
                    prn.print(POSHW.getHeading1());
                    prn.print(POSHW.getHeading2());
                    prn.print(POSHW.getHeading3());
                    prn.print(POSHW.getHeading4());
                    prn.print("REG ID :" + PublicVar.MACNO);
                    prn.print("    รายงานการรับชำระจากลูกหนี้ภายนอก ");
                    prn.print("          AR Payment Report");
                    prn.print("หมายเลขเครื่อง : " + MacNo1 + "..." + MacNo2);
                    prn.print(DatefmtThai.format(date) + " " + "Cashier:" + PublicVar._User + " Mac:" + PublicVar.MACNO);
                    prn.print("----------------------------------------");
                    prn.print("AR Code    เลขที่ใบเสร็จรับเงิน/วันที่  จำนวนเงิน");
                    prn.print("----------------------------------------");
                    
                    
                    mysqlConnect.open(this.getClass());
                    try {
                        try (Statement stmt = mysqlConnect.getConnection().createStatement()) {
                            String SqlQuery = "select * from t_ar "
                                    + "where (fat<>'V') "
                                    + "and (terminal>='" + MacNo1 + "') "
                                    + "and (terminal<='" + MacNo2 + "')";
                            try (ResultSet rs = stmt.executeQuery(SqlQuery)) {
                                while (rs.next()) {
                                    prn.print(PUtility.DataFull(rs.getString("arcode"), 4) + "  " + rs.getString("billno") + "  " + ShowDatefmt.format(rs.getDate("billdate")) + PUtility.DataFull(DecFmt.format(rs.getDouble("amount")), 9));
                                    SumAmt = SumAmt + rs.getDouble("amount");
                                }
                            }
                        }
                    } catch (SQLException e) {
                        MSG.ERR(this, e.getMessage());
                        AppLogUtil.log(ArPaymentReport.class, "error", e);
                    }

                    prn.print("----------------------------------------");
                    prn.print(PUtility.DataFullR("Total Amount  ", 26) + PUtility.DataFull(DecFmt.format(SumAmt), 13));
                    prn.print("----------------------------------------");
                    prn.print("");
                    Double SumCash = 0.0;
                    Double SumCupon = 0.0;
                    int CntBill = 0;
                    try {
                        try (Statement stmt = mysqlConnect.getConnection().createStatement()) {
                            String SqlQuery = "select * from billar "
                                    + "where (fat<>'V') "
                                    + "and (terminal>='" + MacNo1 + "') "
                                    + "and (terminal<='" + MacNo2 + "')";
                            try (ResultSet rs = stmt.executeQuery(SqlQuery)) {
                                while (rs.next()) {
                                    CntBill++;
                                    SumCash = SumCash + rs.getDouble("cash");
                                    SumCupon = SumCupon + rs.getDouble("cupon");
                                }
                            }
                        }
                    } catch (SQLException e) {
                        MSG.ERR(this, e.getMessage());
                        AppLogUtil.log(MemmaterController.class, "error", e);
                    }
                    prn.print(PUtility.DataFullR("     เงินสด Cash              ", 26) + PUtility.DataFull(DecFmt.format(SumCash), 13));
                    prn.print(PUtility.DataFullR("     บัตรกำนัล Coupon          ", 26) + PUtility.DataFull(DecFmt.format(SumCupon), 13));
                    try {
                        try (Statement stmt = mysqlConnect.getConnection().createStatement()) {
                            String SqlQuery = "select * from t_crar "
                                    + "where (fat<>'V') "
                                    + "and (terminal>='" + MacNo1 + "') "
                                    + "and (terminal<='" + MacNo2 + "')";
                            try (ResultSet rs = stmt.executeQuery(SqlQuery)) {
                                while (rs.next()) {
                                    prn.print(PUtility.DataFullR(PUtility.SeekCreditName(rs.getString("crcode") + "                "), 20) + PUtility.DataFull(IntFmt.format(rs.getInt("crcnt")), 6) + PUtility.DataFull(DecFmt.format(rs.getDouble("cramt")), 13));
                                }
                            }
                        }
                    } catch (SQLException e) {
                        MSG.ERR(this, e.getMessage());
                        AppLogUtil.log(MemmaterController.class, "error", e);
                    }

                    prn.print("ยอดรับชำระ AR    : " + PUtility.DataFull(IntFmt.format(CntBill), 6));
                    prn.print("----------------------------------------");
                    prn.print(" ");
                    prn.print("ยอดยกเลิกรายการ การรับชำระจากลูกหนี้ภายนอก");
                    prn.print("AR Pay-No    Amount  Mac  User User Void ");
                    prn.print("----------------------------------------");
                    try {
                        try (Statement stmt = mysqlConnect.getConnection().createStatement()) {
                            String SqlQuery = "select * from billar "
                                    + "where (fat='V') "
                                    + "and (terminal>='" + MacNo1 + "') "
                                    + "and (terminal<='" + MacNo2 + "')";
                            try (ResultSet rs = stmt.executeQuery(SqlQuery)) {
                                while (rs.next()) {
                                    prn.print(rs.getString("ref_no") + "  " + PUtility.DataFull(DecFmt.format(rs.getDouble("stotal")), 9) + "  " + rs.getString("terminal") + "  " + PUtility.DataFull(rs.getString("cashier"), 6) + "  " + PUtility.DataFull(rs.getString("uservoid"), 6));
                                }
                            }
                        }
                    } catch (SQLException e) {
                        MSG.ERR(this, e.getMessage());
                        AppLogUtil.log(MemmaterController.class, "error", e);
                    }

                    prn.print("----------------------------------------");
                    prn.print(" ");
                    prn.print(" ");
                    prn.print(" ");
                    prn.cutPaper();
                    prn.closePrint();
                }
            }
            txtMacNo1.requestFocus();
        }

    }

    private void arPaymentPrintDriver(String MacNo1, String MacNo2) {
        DateConvert dc = new DateConvert();
        String t = "";
        String t1 = "";
        int bill = 0;
        int billVoid = 0;
        double billVoidAmt = 0.00;

        try {
            mysqlConnect.open(this.getClass());

            if (POSHW.getHeading1().trim().length() >= 18) {
                String[] strs = POSHW.getHeading1().trim().replace(" ", Space).split("_");
                for (String data : strs) {
                    t += "colspan=3 align=center><font face=Angsana New size=1>" + data + "_";
                }
            } else {
                t += "colspan=3 align=center><font face=Angsana New size=1>" + POSHW.getHeading1().trim().replace(" ", "&nbsp; ") + "_";
            }
            if (POSHW.getHeading2().trim().length() >= 18) {
                String[] strs = POSHW.getHeading2().trim().replace(" ", Space).split("_");
                for (String data : strs) {
                    t += "colspan=3 align=center><font face=sAngsana New size=1>" + data + "_";
                }
            } else {
                t += "colspan=3 align=center><font face=Angsana New size=1>" + POSHW.getHeading2().trim().replace(" ", "&nbsp; ") + "_";
            }
            t += "colspan=3 align=center><font face=Angsana New size=1>" + (POSHW.getHeading3()).trim() + "_";
            t += "colspan=3 align=center><font face=Angsana New size=1>" + (POSHW.getHeading4()).trim() + "_";
            t += ("colspan=3 align=center><font face=Angsana New size=1>_");
            t += "colspan=3 align=center><font face=Angsana New size=1>" + ("รายงานส่วนลดบัตรคูปองพิเศษ" + "_");
            t += "colspan=3 align=center><font face=Angsana New size=1>" + ("(Daily..Coupon Report)" + "_");
            t += ("colspan=3 align=center><font face=Angsana New size=1>_");
            t += "align=left><font face=Angsana New size=1>" + ("หมายเลขเครื่อง :" + "</td><td colspan=2 align=left><font face=Angsana New size=1>" + MacNo1 + " ..." + MacNo2 + "_");
            t += "colspan=3 align=left><font face=Angsana New size=1>" + ("_");
            t += "colspan=3 align=left><font face=Angsana New size=1>" + "Print Date" + Space + (DatefmtThai.format(date)) + "_";
            t += "colspan=3 align=left><font face=Angsana New size=1>" + "Cashier:" + PublicVar._UserName + TAB + " Mac:" + PublicVar.MACNO + "_";
            t += "colspan=3 align=center><font face=Angsana New size=1>" + ("----------------------------------------------") + "_";
            t += "colspan=3 align=center><font face=Angsana New size=1>" + ("Ar-Code" + Space + "เลขที่ใบเสร็จรับเงิน/วันที่" + Space + "จำนวนเงิน ") + "_";
            t += "colspan=3 align=center><font face=Angsana New size=1>" + ("----------------------------------------------") + "_";

            String sql = "select * from billar order by Ref_No,fat limit 1;";
            try (ResultSet rs = mysqlConnect.executeQuery(sql)) {
                if (rs.next()) {
                    double total = 0.00;
                    double amount = 0.00;
                    double cash = 0.00;
                    double cupon = 0.00;
                    double credit = 0.00;
                    while (rs.next()) {
                        bill++;
                        String Ondate = rs.getString("Ondate");
                        String arCode = rs.getString("ArCode");
                        String terminal = rs.getString("Terminal");
                        String refno = rs.getString("R_Refno");
                        String fat = rs.getString("Fat");
                        String cashier = rs.getString("Cashier");
                        String userVoid = rs.getString("UserVoid");
                        cash += rs.getDouble("Cash");
                        cupon += rs.getDouble("Cupon");
                        credit += rs.getDouble("Credit");
                        total = rs.getDouble("STotal");
                        amount += total;
                        if (!fat.equals("V")) {
                            t += "align=left><font face=Angsana New size=1>" + arCode + TAB + terminal + "/" + refno + Space + dc.dateGetToShow(Ondate) + "</td><td align=left><font face=Angsana New size=1>" + DecFmt.format(total) + "_";
                        } else {
                            billVoid++;
                            t1 += "align=left><font face=Angsana New size=1>" + refno + TAB + total + TAB + terminal + TAB + cashier + TAB + userVoid + "_";
                            billVoidAmt += total;
                        }
                    }
                    t += "colspan=3 align=right><font face=Angsana New size=1>" + "Toal Amount : " + TAB + DecFmt.format(amount) + "_";
                    t += "colspan=2 align=left><font face=Angsana New size=1>" + "เงินสด" + "</td></font><td colspan=2 align=right><font face=Angsana New size=1>" + DecFmt.format(cash) + "_";
                    t += "colspan=2 align=left><font face=Angsana New size=1>" + "บัตรกำนัล" + "</td></font><td colspan=2 align=right><font face=Angsana New size=1>" + DecFmt.format(cupon) + "_";
                    t += "colspan=2 align=left><font face=Angsana New size=1>" + "เครดิต" + "</td></font><td colspan=2 align=right><font face=Angsana New size=1>" + DecFmt.format(credit) + "_";
                    t += "colspan=3 align=right><font face=Angsana New size=1>" + "รับชำระ Ar." + TAB + bill + Space + "บิล" + "_";
                }
            }
        } catch (SQLException e) {
            MSG.ERR(this, e.getMessage());
        } finally {
            mysqlConnect.closeConnection(this.getClass());
        }

        PrinterDriverControl pd = new PrinterDriverControl();
        String[] strs = t.split("_");
        for (String data : strs) {
            pd.addTextIFont(data);
        }
        if (!t1.equals("")) {
            t1 += "colspan=2 align=right><font face=Angsana New size=1>" + "ยอดยกเลิกรายการ : " + Space + billVoid + Space + "บิล" + "</td></font><td colspan=2 align=right><font face=Angsana New size=1>" + DecFmt.format(billVoidAmt) + "_";
            String[] strs1 = t1.split("_");
            for (String data1 : strs1) {
                pd.addTextIFont(data1);
            }
        }

        pd.printHTML();

    }

    public void bntExitClick() {
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntExit;
    private javax.swing.JButton bntOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtMacNo1;
    private javax.swing.JTextField txtMacNo2;
    // End of variables declaration//GEN-END:variables

}
