package com.softpos.floorplan;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Insets;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author nathee
 */
public class FPlanPanel extends javax.swing.JPanel {

    /**
     * Creates new form FPlanPanel
     */
    private final JButton[] buttons = new JButton[100];
    private Font fontA = new Font("Tahoma", Font.PLAIN, 14);

    public FPlanPanel() {
        initComponents();

        buttons[0] = btn1;
        buttons[1] = btn2;
        buttons[2] = btn3;
        buttons[3] = btn4;
        buttons[4] = btn5;
        buttons[5] = btn6;

        buttons[6] = btn7;
        buttons[7] = btn8;
        buttons[8] = btn9;
        buttons[9] = btn10;
        buttons[10] = btn11;
        buttons[11] = btn12;

        buttons[12] = btn13;
        buttons[13] = btn14;
        buttons[14] = btn15;
        buttons[15] = btn16;
        buttons[16] = btn17;
        buttons[17] = btn18;

        buttons[18] = btn19;
        buttons[19] = btn20;
        buttons[20] = btn21;
        buttons[21] = btn22;
        buttons[22] = btn23;
        buttons[23] = btn24;

        buttons[24] = btn25;
        buttons[25] = btn26;
        buttons[26] = btn27;
        buttons[27] = btn28;
        buttons[28] = btn29;
        buttons[29] = btn30;

        buttons[30] = btn31;
        buttons[31] = btn32;
        buttons[32] = btn33;
        buttons[33] = btn34;
        buttons[34] = btn35;
        buttons[35] = btn36;
        
        buttons[36] = btn37;
        buttons[37] = btn38;
        buttons[38] = btn39;
        buttons[39] = btn40;
        buttons[40] = btn41;
        buttons[41] = btn42;
        
        buttons[42] = btn43;
        buttons[43] = btn44;
        buttons[44] = btn45;
        buttons[45] = btn46;
        buttons[46] = btn47;
        buttons[47] = btn48;
        
        buttons[48] = btn49;
        buttons[49] = btn50;
        buttons[50] = btn51;
        buttons[51] = btn52;
        buttons[52] = btn53;
        buttons[53] = btn54;
        
        buttons[54] = btn55;
        buttons[55] = btn56;
        buttons[56] = btn57;
        buttons[57] = btn58;
        buttons[58] = btn59;
        buttons[59] = btn60;
        
        buttons[60] = btn61;
        buttons[61] = btn62;
        buttons[62] = btn63;
        buttons[63] = btn64;
        buttons[64] = btn65;
        buttons[65] = btn66;
        
        buttons[66] = btn67;
        buttons[67] = btn68;
        buttons[68] = btn69;
        buttons[69] = btn70;
        buttons[70] = btn71;
        buttons[71] = btn72;
        
        buttons[72] = btn73;
        buttons[73] = btn74;
        buttons[74] = btn75;
        buttons[75] = btn76;
        buttons[76] = btn77;
        buttons[77] = btn78;
        
        buttons[78] = btn79;
        buttons[79] = btn80;
        buttons[80] = btn81;
        buttons[81] = btn82;
        buttons[82] = btn83;
        buttons[83] = btn84;
        
        buttons[84] = btn85;
        buttons[85] = btn86;
        buttons[86] = btn87;
        buttons[87] = btn88;
        buttons[88] = btn89;
        buttons[89] = btn90;
        
        buttons[90] = btn91;
        buttons[91] = btn92;
        buttons[92] = btn93;
        buttons[93] = btn94;
        buttons[94] = btn95;
        buttons[95] = btn96;
        
        buttons[96] = btn97;
        buttons[97] = btn98;
        buttons[98] = btn99;
        buttons[99] = btn100;
        
        initLoadTableButton();
    }
    
    
    private void initLoadTableButton() {
        for (int i = 0; i < buttons.length; i++) {
            buttons[i] = new JButton("");
            buttons[i].setPreferredSize(new Dimension(50, 50));
            buttons[i].setFocusPainted(false);
            buttons[i].setMargin(new Insets(0, 0, 0, 0));
            buttons[i].setContentAreaFilled(false);
            buttons[i].setBorderPainted(false);
            buttons[i].setOpaque(false);
            buttons[i].setFont(fontA);
            
            for(ActionListener listener: buttons[i].getActionListeners()){
                buttons[i].removeActionListener(listener);
            }
        }
    }

    public JPanel loadData(int index) {
        for (JButton button1 : buttons) {
            button1.setText("Tab:" + index);
        }
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn17 = new javax.swing.JButton();
        btn18 = new javax.swing.JButton();
        btn19 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn23 = new javax.swing.JButton();
        btn24 = new javax.swing.JButton();
        btn25 = new javax.swing.JButton();
        btn26 = new javax.swing.JButton();
        btn27 = new javax.swing.JButton();
        btn28 = new javax.swing.JButton();
        btn29 = new javax.swing.JButton();
        btn30 = new javax.swing.JButton();
        btn31 = new javax.swing.JButton();
        btn32 = new javax.swing.JButton();
        btn33 = new javax.swing.JButton();
        btn34 = new javax.swing.JButton();
        btn35 = new javax.swing.JButton();
        btn36 = new javax.swing.JButton();
        btn37 = new javax.swing.JButton();
        btn38 = new javax.swing.JButton();
        btn39 = new javax.swing.JButton();
        btn40 = new javax.swing.JButton();
        btn41 = new javax.swing.JButton();
        btn42 = new javax.swing.JButton();
        btn43 = new javax.swing.JButton();
        btn44 = new javax.swing.JButton();
        btn45 = new javax.swing.JButton();
        btn46 = new javax.swing.JButton();
        btn47 = new javax.swing.JButton();
        btn48 = new javax.swing.JButton();
        btn49 = new javax.swing.JButton();
        btn50 = new javax.swing.JButton();
        btn51 = new javax.swing.JButton();
        btn52 = new javax.swing.JButton();
        btn53 = new javax.swing.JButton();
        btn54 = new javax.swing.JButton();
        btn55 = new javax.swing.JButton();
        btn56 = new javax.swing.JButton();
        btn57 = new javax.swing.JButton();
        btn58 = new javax.swing.JButton();
        btn59 = new javax.swing.JButton();
        btn60 = new javax.swing.JButton();
        btn61 = new javax.swing.JButton();
        btn62 = new javax.swing.JButton();
        btn63 = new javax.swing.JButton();
        btn64 = new javax.swing.JButton();
        btn65 = new javax.swing.JButton();
        btn66 = new javax.swing.JButton();
        btn67 = new javax.swing.JButton();
        btn68 = new javax.swing.JButton();
        btn69 = new javax.swing.JButton();
        btn70 = new javax.swing.JButton();
        btn71 = new javax.swing.JButton();
        btn72 = new javax.swing.JButton();
        btn73 = new javax.swing.JButton();
        btn74 = new javax.swing.JButton();
        btn75 = new javax.swing.JButton();
        btn76 = new javax.swing.JButton();
        btn77 = new javax.swing.JButton();
        btn78 = new javax.swing.JButton();
        btn79 = new javax.swing.JButton();
        btn80 = new javax.swing.JButton();
        btn81 = new javax.swing.JButton();
        btn82 = new javax.swing.JButton();
        btn83 = new javax.swing.JButton();
        btn84 = new javax.swing.JButton();
        btn85 = new javax.swing.JButton();
        btn86 = new javax.swing.JButton();
        btn87 = new javax.swing.JButton();
        btn88 = new javax.swing.JButton();
        btn89 = new javax.swing.JButton();
        btn90 = new javax.swing.JButton();
        btn91 = new javax.swing.JButton();
        btn92 = new javax.swing.JButton();
        btn93 = new javax.swing.JButton();
        btn94 = new javax.swing.JButton();
        btn95 = new javax.swing.JButton();
        btn96 = new javax.swing.JButton();
        btn97 = new javax.swing.JButton();
        btn98 = new javax.swing.JButton();
        btn99 = new javax.swing.JButton();
        btn100 = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(10, 10));

        btn1.setText("btn1");
        btn1.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn1);

        btn2.setText("btn1");
        btn2.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn2);

        btn3.setText("btn1");
        btn3.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn3);

        btn4.setText("btn1");
        btn4.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn4);

        btn5.setText("btn1");
        btn5.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn5);

        btn6.setText("btn1");
        btn6.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn6);

        btn7.setText("btn1");
        btn7.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn7);

        btn8.setText("btn1");
        btn8.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn8);

        btn9.setText("btn1");
        btn9.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn9);

        btn10.setText("btn1");
        btn10.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn10);

        btn11.setText("btn1");
        btn11.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn11);

        btn12.setText("btn1");
        btn12.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn12);

        btn13.setText("btn1");
        btn13.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn13);

        btn14.setText("btn1");
        btn14.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn14);

        btn15.setText("btn1");
        btn15.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn15);

        btn16.setText("btn1");
        btn16.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn16);

        btn17.setText("btn1");
        btn17.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn17);

        btn18.setText("btn1");
        btn18.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn18);

        btn19.setText("btn1");
        btn19.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn19);

        btn20.setText("btn1");
        btn20.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn20);

        btn21.setText("btn1");
        btn21.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn21);

        btn22.setText("btn1");
        btn22.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn22);

        btn23.setText("btn1");
        btn23.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn23);

        btn24.setText("btn1");
        btn24.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn24);

        btn25.setText("btn1");
        btn25.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn25);

        btn26.setText("btn1");
        btn26.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn26);

        btn27.setText("btn1");
        btn27.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn27);

        btn28.setText("btn1");
        btn28.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn28);

        btn29.setText("btn1");
        btn29.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn29);

        btn30.setText("btn1");
        btn30.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn30);

        btn31.setText("btn1");
        btn31.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn31);

        btn32.setText("btn1");
        btn32.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn32);

        btn33.setText("btn1");
        btn33.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn33);

        btn34.setText("btn1");
        btn34.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn34);

        btn35.setText("btn1");
        btn35.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn35);

        btn36.setText("btn1");
        btn36.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn36);

        btn37.setText("btn1");
        btn37.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn37);

        btn38.setText("btn1");
        btn38.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn38);

        btn39.setText("btn1");
        btn39.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn39);

        btn40.setText("btn1");
        btn40.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn40);

        btn41.setText("btn1");
        btn41.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn41);

        btn42.setText("btn1");
        btn42.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn42);

        btn43.setText("btn1");
        btn43.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn43);

        btn44.setText("btn1");
        btn44.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn44);

        btn45.setText("btn1");
        btn45.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn45);

        btn46.setText("btn1");
        btn46.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn46);

        btn47.setText("btn1");
        btn47.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn47);

        btn48.setText("btn1");
        btn48.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn48);

        btn49.setText("btn1");
        btn49.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn49);

        btn50.setText("btn1");
        btn50.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn50);

        btn51.setText("btn1");
        btn51.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn51);

        btn52.setText("btn1");
        btn52.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn52);

        btn53.setText("btn1");
        btn53.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn53);

        btn54.setText("btn1");
        btn54.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn54);

        btn55.setText("btn1");
        btn55.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn55);

        btn56.setText("btn1");
        btn56.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn56);

        btn57.setText("btn1");
        btn57.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn57);

        btn58.setText("btn1");
        btn58.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn58);

        btn59.setText("btn1");
        btn59.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn59);

        btn60.setText("btn1");
        btn60.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn60);

        btn61.setText("btn1");
        btn61.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn61);

        btn62.setText("btn1");
        btn62.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn62);

        btn63.setText("btn1");
        btn63.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn63);

        btn64.setText("btn1");
        btn64.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn64);

        btn65.setText("btn1");
        btn65.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn65);

        btn66.setText("btn1");
        btn66.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn66);

        btn67.setText("btn1");
        btn67.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn67);

        btn68.setText("btn1");
        btn68.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn68);

        btn69.setText("btn1");
        btn69.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn69);

        btn70.setText("btn1");
        btn70.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn70);

        btn71.setText("btn1");
        btn71.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn71);

        btn72.setText("btn1");
        btn72.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn72);

        btn73.setText("btn1");
        btn73.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn73);

        btn74.setText("btn1");
        btn74.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn74);

        btn75.setText("btn1");
        btn75.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn75);

        btn76.setText("btn1");
        btn76.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn76);

        btn77.setText("btn1");
        btn77.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn77);

        btn78.setText("btn1");
        btn78.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn78);

        btn79.setText("btn1");
        btn79.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn79);

        btn80.setText("btn1");
        btn80.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn80);

        btn81.setText("btn1");
        btn81.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn81);

        btn82.setText("btn1");
        btn82.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn82);

        btn83.setText("btn1");
        btn83.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn83);

        btn84.setText("btn1");
        btn84.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn84);

        btn85.setText("btn1");
        btn85.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn85);

        btn86.setText("btn1");
        btn86.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn86);

        btn87.setText("btn1");
        btn87.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn87);

        btn88.setText("btn1");
        btn88.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn88);

        btn89.setText("btn1");
        btn89.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn89);

        btn90.setText("btn1");
        btn90.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn90);

        btn91.setText("btn1");
        btn91.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn91);

        btn92.setText("btn1");
        btn92.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn92);

        btn93.setText("btn1");
        btn93.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn93);

        btn94.setText("btn1");
        btn94.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn94);

        btn95.setText("btn1");
        btn95.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn95);

        btn96.setText("btn1");
        btn96.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn96);

        btn97.setText("btn1");
        btn97.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn97);

        btn98.setText("btn1");
        btn98.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn98);

        btn99.setText("btn1");
        btn99.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn99);

        btn100.setText("btn1");
        btn100.setPreferredSize(new java.awt.Dimension(50, 50));
        add(btn100);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn100;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn17;
    private javax.swing.JButton btn18;
    private javax.swing.JButton btn19;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn23;
    private javax.swing.JButton btn24;
    private javax.swing.JButton btn25;
    private javax.swing.JButton btn26;
    private javax.swing.JButton btn27;
    private javax.swing.JButton btn28;
    private javax.swing.JButton btn29;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn30;
    private javax.swing.JButton btn31;
    private javax.swing.JButton btn32;
    private javax.swing.JButton btn33;
    private javax.swing.JButton btn34;
    private javax.swing.JButton btn35;
    private javax.swing.JButton btn36;
    private javax.swing.JButton btn37;
    private javax.swing.JButton btn38;
    private javax.swing.JButton btn39;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn40;
    private javax.swing.JButton btn41;
    private javax.swing.JButton btn42;
    private javax.swing.JButton btn43;
    private javax.swing.JButton btn44;
    private javax.swing.JButton btn45;
    private javax.swing.JButton btn46;
    private javax.swing.JButton btn47;
    private javax.swing.JButton btn48;
    private javax.swing.JButton btn49;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn50;
    private javax.swing.JButton btn51;
    private javax.swing.JButton btn52;
    private javax.swing.JButton btn53;
    private javax.swing.JButton btn54;
    private javax.swing.JButton btn55;
    private javax.swing.JButton btn56;
    private javax.swing.JButton btn57;
    private javax.swing.JButton btn58;
    private javax.swing.JButton btn59;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn60;
    private javax.swing.JButton btn61;
    private javax.swing.JButton btn62;
    private javax.swing.JButton btn63;
    private javax.swing.JButton btn64;
    private javax.swing.JButton btn65;
    private javax.swing.JButton btn66;
    private javax.swing.JButton btn67;
    private javax.swing.JButton btn68;
    private javax.swing.JButton btn69;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn70;
    private javax.swing.JButton btn71;
    private javax.swing.JButton btn72;
    private javax.swing.JButton btn73;
    private javax.swing.JButton btn74;
    private javax.swing.JButton btn75;
    private javax.swing.JButton btn76;
    private javax.swing.JButton btn77;
    private javax.swing.JButton btn78;
    private javax.swing.JButton btn79;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn80;
    private javax.swing.JButton btn81;
    private javax.swing.JButton btn82;
    private javax.swing.JButton btn83;
    private javax.swing.JButton btn84;
    private javax.swing.JButton btn85;
    private javax.swing.JButton btn86;
    private javax.swing.JButton btn87;
    private javax.swing.JButton btn88;
    private javax.swing.JButton btn89;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btn90;
    private javax.swing.JButton btn91;
    private javax.swing.JButton btn92;
    private javax.swing.JButton btn93;
    private javax.swing.JButton btn94;
    private javax.swing.JButton btn95;
    private javax.swing.JButton btn96;
    private javax.swing.JButton btn97;
    private javax.swing.JButton btn98;
    private javax.swing.JButton btn99;
    // End of variables declaration//GEN-END:variables

    private void loadData0() {

    }
}
