/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.SoftwareAutoRun;

import com.softpos.pos.core.controller.BalanceControl;
import com.softpos.pos.core.controller.EmployControl;
import com.softpos.pos.core.controller.TableFileControl;
import com.softpos.pos.core.model.BalanceBean;
import com.softpos.pos.core.model.TableFileBean;
import database.MySQLConnect;
import java.awt.Color;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import util.DateConvert;
import util.JTableUtility;
import util.MSG;

/**
 *
 * @author Administrator
 */
public class setTimePreOrder extends javax.swing.JFrame {

    /**
     * Creates new form setTimePreOrder
     */
    private DefaultTableModel model;

    public setTimePreOrder() {
        initComponents();
        JTableHeader header = tbShowBalance.getTableHeader();
        header.setFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 12));
        JTableUtility.alignColumn(tbShowBalance, 0, "left");
        JTableUtility.alignColumn(tbShowBalance, 1, "left");
        JTableUtility.alignColumn(tbShowBalance, 2, "left");
        JTableUtility.alignColumn(tbShowBalance, 3, "left");
        JTableUtility.alignColumn(tbShowBalance, 4, "right");
        JTableUtility.alignColumn(tbShowBalance, 5, "center");
        JTableUtility.alignColumn(tbShowBalance, 6, "left");
        lblRemark.setText("***หมายเหตุ การใส่ช่องเวลา(ตัวอย่าง) 10.03 ต้องครบ 5 หลัก และต้องกด Enter ทุกครั้งเมื่อใส่เวลาเสร็จ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbShowBalance = new javax.swing.JTable();
        btnCancel = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtEmp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTable = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblEmploy = new javax.swing.JLabel();
        txtCustomer = new javax.swing.JLabel();
        lblRemark = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("PreOrder / Reserved");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSave.setText("บันทึก (Save)");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        tbShowBalance.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        tbShowBalance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "จำนวน", "อาหาร", "เครื่องดื่ม", "อื่นๆ", "ราคา", "เวลา", "รหัสสินค้า"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbShowBalance);
        if (tbShowBalance.getColumnModel().getColumnCount() > 0) {
            tbShowBalance.getColumnModel().getColumn(0).setMaxWidth(50);
            tbShowBalance.getColumnModel().getColumn(1).setMinWidth(150);
            tbShowBalance.getColumnModel().getColumn(2).setMinWidth(150);
            tbShowBalance.getColumnModel().getColumn(3).setMinWidth(150);
            tbShowBalance.getColumnModel().getColumn(6).setMaxWidth(0);
        }

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCancel.setText("ยกเลิก (Cancel)");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnExit.setText("ออก (Exit)");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtEmp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtEmp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("พนักงาน");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("เบอร์โต๊ะ");

        txtTable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTable.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTableActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("ลูกค้า");

        lblEmploy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmploy.setText("พนักงาน");

        txtCustomer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCustomer.setText("0");

        lblRemark.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRemark.setForeground(new java.awt.Color(255, 0, 51));
        lblRemark.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRemark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTable, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEmploy, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 197, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTable, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEmploy, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRemark, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTableActionPerformed
        // TODO add your handling code here:

        TableFileControl tb = new TableFileControl();
        TableFileBean bean = new TableFileBean();
        bean = tb.getData(txtTable.getText());

        if (txtTable.getText().equals("") || txtTable.getText().isEmpty() || txtTable.getText().equals("null")) {
            MSG.NOTICE("กรุณากรอก เบอร์โต๊ะอีกครั้ง");
            txtTable.selectAll();
            txtTable.requestFocus();
        }
        if (!bean.getTcode().equals("null")) {
            txtCustomer.setText(bean.getTCustomer() + " คน");
            txtEmp.selectAll();
            txtEmp.requestFocus();
            EmployControl empControl = new EmployControl();
            String empName = empControl.empName(txtEmp.getText());
            if (empName.equals("")) {
                lblEmploy.setText("ไม่พบรหัสพนักงาน");
            } else {
                txtEmp.selectAll();
                txtEmp.requestFocus();
                lblEmploy.setText(empName);

            }
        }


    }//GEN-LAST:event_txtTableActionPerformed

    private void txtEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpActionPerformed
        EmployControl empControl = new EmployControl();
        lblEmploy.setText(empControl.empName(txtEmp.getText()));
        getDataTable(txtTable.getText());


    }//GEN-LAST:event_txtEmpActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        setPreOrderTime(txtTable.getText().trim());
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setNewScreen();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed
    private void getDataTable(String tableNo) {
        TableFileControl tb = new TableFileControl();
        TableFileBean bean = new TableFileBean();
        bean = tb.getData(txtTable.getText());
        if (bean.getTcode().equals("null")) {

            MSG.NOTICE("ไม่พบเบอร์โต๊ะ กรุณากรอกใหม่");
        } else {
            txtCustomer.setText(bean.getTCustomer() + " คน ");
            model = (DefaultTableModel) tbShowBalance.getModel();
            tbShowBalance.setShowGrid(true);
            tbShowBalance.setGridColor(Color.gray);
            tbShowBalance.setRowHeight(45);
            int rowCount = model.getRowCount();
            for (int i = 0; i < rowCount; i++) {
                model.removeRow(0);
            }
            BalanceControl balanceControl = new BalanceControl();
            List<BalanceBean> listBalance = balanceControl.getAllBalanceNoVoidSum(tableNo);

            for (BalanceBean balanceBean : listBalance) {
                DecimalFormat QtyIntFmt = new DecimalFormat("#,##0");

                String rEtd = balanceBean.getR_ETD();
                String PName = rEtd + " " + balanceBean.getR_PName();
                String newName1 = getNewPNameWrap(PName);
                String newName2 = getNewPNameWrap(PName);
                String newName3 = getNewPNameWrap(PName);
                String r_type = balanceBean.getR_Type();
                switch (r_type) {
                    case "1":
                        newName2 = "";
                        newName3 = "";
                        break;
                    case "2":
                        newName1 = "";
                        newName3 = "";
                        break;
                    case "3":
                        newName1 = "";
                        newName2 = "";
                        break;

                }
                Object[] input = {
                    QtyIntFmt.format(balanceBean.getR_Quan()),
                    newName1,
                    newName2,
                    newName3,
                    QtyIntFmt.format(balanceBean.getR_Price()),
                    "",
                    balanceBean.getR_PluCode()
                };
                model.addRow(input);

            }
        }
    }

    private void setNewScreen() {
        txtTable.setText("");
        txtTable.requestFocus();
        txtEmp.setText("");
        lblEmploy.setText("พนักงาน");
        txtCustomer.setText("0 คน");
        int rowCount = model.getRowCount();
        if (rowCount > 0) {
            for (int i = 0; i < rowCount; i++) {
                model.removeRow(0);
            }
        }

    }

    private void setPreOrderTime(String tableNo) {
        DateConvert dc = new DateConvert();
        if (txtTable.getText().equals("")) {

        } else {
            int size = model.getRowCount();
            if (size > 0) {
                DefaultTableModel model1 = (DefaultTableModel) tbShowBalance.getModel();
                MySQLConnect mysql = new MySQLConnect();
                try {
                    mysql.open();
                    String sqlDel = "delete from preordertime where r_table='" + tableNo + "';";
                    mysql.getConnection().createStatement().executeUpdate(sqlDel);
                    for (int i = 0; i < model1.getRowCount(); i++) {
                        if (model.getValueAt(i, 5) == null) {
                            System.out.println("line is null");
                            MSG.NOTICE("ไม่สามารถบันทึกข้อมูลได้ กรุณาตรวจสอบช่องกำหนดเวลา");
                            break;
                        } else {
                            String time = model1.getValueAt(i, 5).toString().replace("NULL", "");
                            if (time.equals("")) {
                                time = "00:00:00";
                            }
                            String sql = "insert into preordertime (R_Table, R_Date, R_TimePrint, R_TimeUpdate, R_Emp, R_Plucode, Flage_Print"
                                    + ")values("
                                    + "'" + tableNo + "','" + dc.GetCurrentDate() + "','" + time + "','" + dc.GetCurrentTime() + "','" + txtEmp.getText() + "','" + model.getValueAt(i, 6) + "','N');";

                            try {

                                mysql.getConnection().createStatement().executeUpdate(sql);
                                System.out.println(time);
                            } catch (Exception e) {
                                MSG.ERR(e.toString());
                            }
                        }

                    }
                    MSG.NOTICE("บันทึกข้อมูลเรียบร้อย");
                    setNewScreen();
                } catch (Exception e) {
                    MSG.ERR(e.toString());
                } finally {
                    mysql.close();
                }

            }
        }

    }

    String getNewPNameWrap(String PName) {
        String[] names = new String[2];
        if (PName.length() > 50) {
            names[0] = PName.substring(0, 50);
            names[1] = PName.substring(50, PName.length());
        } else {
            return PName;
        }

        if (names[0] == null) {
            names[0] = "";
        }
        if (names[1] == null) {
            names[1] = "";
        }

        return names[0] + "<br>" + names[1];
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(setTimePreOrder.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(setTimePreOrder.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(setTimePreOrder.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(setTimePreOrder.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new setTimePreOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmploy;
    private javax.swing.JLabel lblRemark;
    private javax.swing.JTable tbShowBalance;
    private javax.swing.JLabel txtCustomer;
    private javax.swing.JTextField txtEmp;
    private javax.swing.JTextField txtTable;
    // End of variables declaration//GEN-END:variables
}
