package com.softpos.main.program;

import com.softpos.pos.core.controller.CreditPaymentRec;
import com.softpos.pos.core.controller.POSConfigSetup;
import com.softpos.pos.core.controller.PPrint;
import com.softpos.pos.core.controller.PUtility;
import com.softpos.pos.core.controller.PublicVar;
import com.softpos.pos.core.controller.Value;
import com.softpos.pos.core.model.TranRecord;
import database.MySQLConnect;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import util.AppLogUtil;
import util.MSG;

public class CopyBill extends javax.swing.JDialog {

    Date date = new Date();
    TranRecord[] MyArray;
    int ArraySize;
    PPrint prn = new PPrint();
    CreditPaymentRec[] CreditArray;
    POSConfigSetup CONFIG;

    public CopyBill(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        PublicVar.SmpCouponArray = null;
        CONFIG = POSConfigSetup.Bean();
        /**
         * * OPEN CONNECTION **
         */
        MySQLConnect mysql = new MySQLConnect();
        mysql.open();
        try {
            Statement stmt = mysql.getConnection().createStatement();
            String SqlQuery = "select * from billno where b_macno='" + Value.MACNO + "'";
            ResultSet rs = stmt.executeQuery(SqlQuery);
            while (rs.next()) {
                txtBillNo.setText(rs.getString("b_refno"));
            }
            rs.close();
            stmt.close();
        } catch (SQLException e) {
            MSG.ERR(e.getMessage());
            AppLogUtil.log(CopyBill.class, "error", e.getMessage());
        } finally {
            mysql.close();
        }

        txtCopy.setText(Integer.toString(CONFIG.getP_BillCopy()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBillNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCopy = new javax.swing.JFormattedTextField();
        bntOK = new javax.swing.JButton();
        bntExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("พิมพ์สำเนาใบเสร็จรับเงิน");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("กรุณาป้อนเลขที่บิล และจำนวน Copy ที่ต้องการ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("เลขที่บิล (Receipt No)");

        txtBillNo.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        txtBillNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBillNoActionPerformed(evt);
            }
        });
        txtBillNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBillNoKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("จำนวน Copy");

        txtCopy.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtCopy.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCopy.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        txtCopy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCopyKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtCopy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bntOK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bntOK.setText("F5-ตกลง (OK)");
        bntOK.setFocusable(false);
        bntOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntOKActionPerformed(evt);
            }
        });

        bntExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bntExit.setText("ESC-ออก (Exit)");
        bntExit.setFocusable(false);
        bntExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(bntOK, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntExit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntExit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntOK, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(527, 182));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void txtBillNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBillNoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtBillNoActionPerformed

private void txtBillNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBillNoKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        txtCopy.requestFocus();
    }
    if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
        bntExitClick();
    }
    if (evt.getKeyCode() == KeyEvent.VK_F5) {
        bntOKClick();
    }

}//GEN-LAST:event_txtBillNoKeyPressed

private void txtCopyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCopyKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
        bntExitClick();
    } else if (evt.getKeyCode() == KeyEvent.VK_F5) {
        bntOKClick();
    }
}//GEN-LAST:event_txtCopyKeyPressed

    private void bntOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntOKActionPerformed
        bntOKClick();
    }//GEN-LAST:event_bntOKActionPerformed

    private void bntExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExitActionPerformed
        bntExitClick();
    }//GEN-LAST:event_bntExitActionPerformed

    private void actionPrint() {
        String BillNo = txtBillNo.getText();
        /**
         * * OPEN CONNECTION **
         */
        MySQLConnect mysql = new MySQLConnect();
        mysql.open();
        try {
            Statement stmt = mysql.getConnection().createStatement();
            String SqlQuery = "select * from billno "
                    + "where (b_macno='" + Value.MACNO + "') "
                    + "and (b_refno='" + BillNo + "')";
            ResultSet rs = stmt.executeQuery(SqlQuery);
            if (rs.next()) {
                processCopyBill();
            } else {
                MSG.WAR(this, "ไม่พบใบเสร็จรับเงินเลขที่ " + txtBillNo.getText() + "  ในฐานข้อมูล...");
                txtBillNo.selectAll();
                txtBillNo.requestFocus();
            }
            rs.close();
            stmt.close();
        } catch (SQLException e) {
            MSG.ERR(e.getMessage());
            AppLogUtil.log(CopyBill.class, "error", e.getMessage());
        } finally {
            mysql.close();
        }
    }

    private void bntOKClick() {
        actionPrint();
    }

    private void processCopyBill() {
        int CopyPrn = Integer.parseInt(txtCopy.getText());
        String BillNo = txtBillNo.getText();
        //Load Data From BillNo
        int billcopy = 0;
        /**
         * * OPEN CONNECTION **
         */
        MySQLConnect mysql = new MySQLConnect();
        mysql.open();
        try {
            Statement stmt = mysql.getConnection().createStatement();
            String SqlQuery = "select * from billno "
                    + "where (b_macno='" + Value.MACNO + "') "
                    + "and (b_refno='" + BillNo + "')";
            ResultSet rs = stmt.executeQuery(SqlQuery);
            if (rs.next()) {
                PublicVar.TableRec_RefNo = rs.getString("b_refno");
                PublicVar.TableRec_OnDate = rs.getDate("b_ondate");
                PublicVar.TableRec_OnTime = rs.getString("b_ontime");
                PublicVar.TableRec_TCode = rs.getString("b_table");
                PublicVar.TableRec_MacNo = rs.getString("b_macno");
                PublicVar.TableRec_Cashier = rs.getString("b_cashier");
                PublicVar.TableRec_TLogInTime = "";
                PublicVar.TableRec_TCurTime = "";
                PublicVar.TableRec_TLoginDate = date;
                PublicVar.TableRec_TOnAct = "";
                PublicVar.TableRec_TCustomer = rs.getInt("b_cust");
                PublicVar.TableRec_ETD = rs.getString("b_etd");
                PublicVar.TableRec_TAmount = rs.getDouble("b_total");
                PublicVar.TableRec_Food = rs.getDouble("b_food");
                PublicVar.TableRec_Drink = rs.getDouble("b_drink");
                PublicVar.TableRec_Product = rs.getDouble("b_product");
                PublicVar.TableRec_Service = rs.getDouble("b_service");
                PublicVar.TableRec_ServiceAmt = rs.getDouble("b_serviceamt");
                PublicVar.TableRec_FastDisc = rs.getString("b_fastdisc");
                PublicVar.TableRec_FastDiscAmt = rs.getDouble("b_fastdiscamt");
                PublicVar.TableRec_EmpDisc = rs.getString("b_empdisc");
                PublicVar.TableRec_EmpDiscAmt = rs.getDouble("b_empdiscamt");
                PublicVar.TableRec_TrainDisc = rs.getString("b_traindisc");
                PublicVar.TableRec_TrainDiscAmt = rs.getDouble("b_traindiscamt");
                PublicVar.TableRec_MemDisc = rs.getString("b_memdisc");
                PublicVar.TableRec_MemDiscAmt = rs.getDouble("b_memdiscamt");
                PublicVar.TableRec_SubDisc = rs.getString("b_subdisc");
                PublicVar.TableRec_SubDiscAmt = rs.getDouble("b_subdiscamt");
                PublicVar.TableRec_DiscBath = rs.getDouble("b_subdiscbath");
                PublicVar.TableRec_ProDiscAmt = rs.getDouble("b_prodiscamt");
                PublicVar.TableRec_SpaDiscAmt = rs.getDouble("b_spadiscamt");
                PublicVar.TableRec_CuponDiscAmt = rs.getDouble("b_cupondiscamt");
                PublicVar.TableRec_ItemDiscAmt = rs.getDouble("b_itemdiscamt");
                PublicVar.TableRec_MemCode = rs.getString("b_memcode");
                PublicVar.TableRec_MemName = rs.getString("b_memname");
                PublicVar.TableRec_MemBegin = null;
                PublicVar.TableRec_MemEnd = null;
                PublicVar.TableRec_MemBrid = null;
                PublicVar.TableRec_MemCurAmt = rs.getDouble("b_sumscore");
                PublicVar.TableRec_Score = rs.getDouble("b_memcursum");
                PublicVar.TableRec_SumScoreal = rs.getDouble("b_sumscore");
                PublicVar.TableRec_NetTotal = rs.getDouble("b_nettotal");
                PublicVar.TableRec_NetFood = rs.getDouble("b_netfood");
                PublicVar.TableRec_NetDrink = rs.getDouble("b_netdrink");
                PublicVar.TableRec_NetProduct = rs.getDouble("b_netproduct");
                PublicVar.TableRec_NetVat = rs.getDouble("b_netvat");
                PublicVar.TableRec_NetNonVat = rs.getDouble("b_netnonvat");
                PublicVar.TableRec_Vat = rs.getDouble("b_vat");
                PublicVar.TableRec_ArCode = rs.getString("b_accrcode");
                PublicVar.TableRec_AccrCr = rs.getInt("b_accrcr");
                PublicVar.TableRec_ArPayment = rs.getDouble("b_accramt");
                PublicVar.TableRec_PayAmt = rs.getDouble("b_payamt");
                PublicVar.TableRec_Ton = rs.getDouble("b_ton");
                PublicVar.TableRec_Earnest = rs.getDouble("b_earnest");
                PublicVar.TableRec_Gift_Voucher = rs.getDouble("b_giftvoucher");
                PublicVar.TableRec_Cash = rs.getDouble("b_cash");
                PublicVar.TableRec_Cr_Bank = rs.getString("b_crbank");   //For SMP
                PublicVar.TableRec_Cr_CardAmt = rs.getDouble("b_crcardamt");
                PublicVar.TableRec_Cr_CurPoint = rs.getInt("b_crcurpoint");
                PublicVar.TableRec_Cr_SumPoint = rs.getInt("b_crsumpoint");
                PublicVar.TableRec_Cr_Name1 = "";
                PublicVar.TableRec_Cr_Charge = rs.getDouble("b_crcharge1");
                PublicVar.TableRec_Cr_ChargeAmt = rs.getDouble("b_crchargeamt1");
                PublicVar.TableRec_Cr_Redule = 0.00;
                PublicVar.TableRec2_Cr_Code1 = rs.getString("b_crcode1");
                PublicVar.TableRec_Cr_CardNo1 = rs.getString("b_cardno1");
                PublicVar.TableRec_Cr_App_Code1 = rs.getString("b_appcode1");
                PublicVar.TableRec_Cr_Amount1 = rs.getDouble("b_cramt1");
                PublicVar.TableRec_PrintTotal = 0.00;
                PublicVar.TableRec_PrnCnt = 0;
                PublicVar.TableRec_BillCopy = 0;
                PublicVar.TableRec_PrnTime1 = "";
                PublicVar.TableRec_PrnTime2 = "";
                PublicVar.TableRec_BranCode = rs.getString("b_bran");
                PublicVar.TableRec_BranName = rs.getString("b_branname");
                PublicVar.TableRec_BranTel = rs.getString("b_tel");
                PublicVar.TableRec_BranTime = rs.getString("b_rectime");
                billcopy = rs.getInt("b_billcopy");
            } else {
                MSG.WAR("ไม่พบใบเสร็จรับเงินเลขที่ " + txtBillNo.getText() + "  ในฐานข้อมูล...");
                this.dispose();
            }
            rs.close();
            stmt.close();
        } catch (SQLException e) {
            MSG.ERR(e.getMessage());
            AppLogUtil.log(CopyBill.class, "error", e.getMessage());
        }

        //Load Data From T_Sale
        try {
            Statement stmt = mysql.getConnection().createStatement();
            String LoadBalance = "select * from t_sale "
                    + "where (macno='" + Value.MACNO + "') "
                    + "and (r_refno='" + BillNo + "')";
            ResultSet rs = stmt.executeQuery(LoadBalance);
            PublicVar.P_ItemCount = 0;
            MyArray = null;
            MyArray = new TranRecord[1];
            while (rs.next()) {
                PublicVar.P_ItemCount++;
                TranRecord TranRec = new TranRecord();
                TranRec.R_Index = rs.getString("r_index");
                TranRec.R_Date = rs.getDate("r_date");
                TranRec.R_Table = rs.getString("r_table");
                TranRec.R_Time = rs.getString("r_time");
                TranRec.Macno = rs.getString("macno");
                TranRec.Cashier = rs.getString("cashier");
                TranRec.R_Emp = rs.getString("r_emp");
                TranRec.R_Set = rs.getString("r_set");
                TranRec.R_Stock = rs.getString("r_stock");
                TranRec.R_PluCode = rs.getString("r_plucode");
                TranRec.R_PName = rs.getString("r_pname");
                TranRec.R_Unit = rs.getString("r_unit");
                TranRec.R_Group = rs.getString("r_group");
                TranRec.R_Status = rs.getString("r_status");
                TranRec.R_Normal = rs.getString("r_normal");
                TranRec.R_Discount = rs.getString("r_discount");
                TranRec.R_Service = rs.getString("r_service");
                TranRec.R_Vat = rs.getString("r_vat");
                TranRec.R_Type = rs.getString("r_type");
                TranRec.R_ETD = rs.getString("r_etd");
                TranRec.R_Quan = rs.getDouble("r_quan");
                TranRec.R_Price = rs.getDouble("r_price");
                TranRec.R_Total = rs.getDouble("r_total");
                TranRec.R_PrType = rs.getString("r_prtype");
                TranRec.R_PrCode = rs.getString("r_prcode");
                TranRec.R_PrDisc = rs.getDouble("r_prdisc");
                TranRec.R_PrBath = rs.getDouble("r_prbath");
                TranRec.R_PrAmt = rs.getDouble("r_pramt");
                TranRec.R_PrQuan = rs.getDouble("r_prquan");
                TranRec.R_Redule = rs.getDouble("r_redule");
                TranRec.R_KIC = rs.getString("r_kic");
                TranRec.R_KicPrint = rs.getString("r_kicprint");
                TranRec.R_Void = rs.getString("r_void");
                TranRec.R_VoidUser = rs.getString("r_voiduser");
                TranRec.R_VoidTime = rs.getString("r_voidtime");
                TranRec.R_DiscBath = rs.getDouble("r_discbath");
                if (PublicVar.P_ItemCount > 1) {
                    MyArray = PUtility.addArray(MyArray);
                }
                ArraySize = MyArray.length;
                MyArray[ArraySize - 1] = TranRec;
            }
            rs.close();
            stmt.close();

        } catch (SQLException e) {
            MSG.ERR(e.getMessage());
            AppLogUtil.log(CopyBill.class, "error", e.getMessage());
        } finally {
            mysql.close();
        }

        if (CONFIG.getP_BillCopyOne().equals("Y") & (billcopy > 0)) {
            MSG.WAR("บิลเลขที่ " + BillNo + "  ได้มีการพิมพ์สำเนาไปแล้ว...ไม่สามารถพิมพ์ได้อีก");
            txtBillNo.requestFocus();
        } else {
            if (CopyPrn > CONFIG.getP_BillCopy()) {
                CopyPrn = CONFIG.getP_BillCopy();
                txtCopy.setText(Integer.toString(CopyPrn));
            }
            for (int i = 1; i <= CopyPrn; i++) {
                prn.PrintBillCopy(MyArray, BillNo, i, CreditArray);
            }
            try {
                mysql.open();
                Statement stmt = mysql.getConnection().createStatement();
                String SqlQuery = "update billno set "
                        + "b_billcopy=b_billcopy+1 "
                        + "where (b_refno='" + BillNo + "') "
                        + "and (b_macno='" + Value.MACNO + "')";
                stmt.executeUpdate(SqlQuery);
                stmt.close();
            } catch (SQLException e) {
                MSG.ERR(e.getMessage());
                AppLogUtil.log(CopyBill.class, "error", e.getMessage());
            } finally {
                mysql.close();
            }
            this.dispose();
        }
    }

    private void bntExitClick() {
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntExit;
    private javax.swing.JButton bntOK;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtBillNo;
    private javax.swing.JFormattedTextField txtCopy;
    // End of variables declaration//GEN-END:variables
}
