package com.softpos.main.program;

import com.softpos.pos.core.controller.PublicVar;
import com.softpos.pos.core.controller.Value;
import database.MySQLConnect;
import java.awt.Color;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import util.AppLogUtil;
import util.MSG;

public final class Giftvoucher extends javax.swing.JDialog {

    private DefaultTableModel model;
    private SimpleDateFormat Datefmtshow = new SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH);
    private Double giftAmt;

    /**
     * Creates new form Giftvoucher
     *
     * @param parent
     * @param modal
     */
    public Giftvoucher(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        PublicVar.ReturnString = "";
        model = (DefaultTableModel) tblShow.getModel();
        tblShow.setShowGrid(true);
        tblShow.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblShow.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblShow.setRowSelectionAllowed(true);
        tblShow.setGridColor(Color.gray);

        JTableHeader header = tblShow.getTableHeader();
        header.setBackground(Color.yellow);
        header.setFont(new java.awt.Font("Norasi", java.awt.Font.PLAIN, 16));

        int[] ColSize = {60, 50, 50, 100, 200, 80, 90};
        for (int i = 0; i < 7; i++) {
            TableColumn col = tblShow.getColumnModel().getColumn(i);
            col.setPreferredWidth(ColSize[i]);
        }

        activateModuel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtGiftNo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShow = new javax.swing.JTable();
        bntClearAll = new javax.swing.JButton();
        bntOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("รายการบัตรกำนัล/บัตรของขวัญ (Giftvouchar)");
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        jLabel1.setText("Barcode");

        txtGiftNo.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        txtGiftNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGiftNoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGiftNo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(369, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGiftNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblShow.setFont(new java.awt.Font("Norasi", 0, 16)); // NOI18N
        tblShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ประเภท", "แบบ", "ล็อต", "วันหมดอายุ", "Code", "NO #", "จำนวนเงิน"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblShow.setRequestFocusEnabled(false);
        tblShow.setRowHeight(35);
        tblShow.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblShowKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblShow);

        bntClearAll.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntClearAll.setText("F3-Clear All");
        bntClearAll.setMargin(new java.awt.Insets(1, 1, 1, 1));
        bntClearAll.setRequestFocusEnabled(false);
        bntClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntClearAllActionPerformed(evt);
            }
        });

        bntOK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntOK.setText("F5-จบการทำงาน");
        bntOK.setMargin(new java.awt.Insets(1, 1, 1, 1));
        bntOK.setRequestFocusEnabled(false);
        bntOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bntClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntOK, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntOK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(634, 309));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void bntClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntClearAllActionPerformed
    bntClearAllClick();
}//GEN-LAST:event_bntClearAllActionPerformed

private void bntOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntOKActionPerformed
    bntOKClick();
}//GEN-LAST:event_bntOKActionPerformed

private void txtGiftNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiftNoKeyPressed
    switch (evt.getKeyCode()) {
        case KeyEvent.VK_ESCAPE:
            bntOKClick();
            break;
        case KeyEvent.VK_ENTER:
            tGiftNoExit();
            break;
        case KeyEvent.VK_F5:
            bntOKClick();
            break;
        case KeyEvent.VK_F3:
            bntClearAllClick();
            break;
        default:
            break;
    }

}//GEN-LAST:event_txtGiftNoKeyPressed

private void tblShowKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblShowKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_F5) {
        bntOKClick();
    }
    if (evt.getKeyCode() == KeyEvent.VK_F3) {
        bntClearAllClick();
    }
}//GEN-LAST:event_tblShowKeyPressed
    public void bntOKClick() {
        this.dispose();
    }

    public void bntClearAllClick() {
        MySQLConnect mysql = new MySQLConnect();
        mysql.open();
        try {
            PreparedStatement prm = mysql.getConnection().prepareStatement("delete from tempgift where (macno=?) ");
            prm.setString(1, Value.MACNO);
            prm.executeUpdate();

            clearGrid();
        } catch (SQLException e) {
            MSG.ERR(e.getMessage());
            AppLogUtil.log(Giftvoucher.class, "error", e.getMessage());
        } finally {
            mysql.close();
        }

        txtGiftNo.setText("");
    }

    void activateModuel() {
        txtGiftNo.setText("");
        clearGrid();
        showDataToGrid();
    }

    public void clearGrid() {
        int rowCount = model.getRowCount();
        for (int i = 0; i <= rowCount - 1; i++) {
            model.removeRow(0);
        }
    }

    public void tGiftNoExit() {
        String giftBarcode = txtGiftNo.getText().trim();
        if (!giftBarcode.equals("")) {
            if ((giftBarcode.length() == 20) || (giftBarcode.length() == 26)) {
                getValidVoucher(giftBarcode);
                txtGiftNo.setText("");
                txtGiftNo.requestFocus();
            } else {
                MSG.ERR("Barcode บัตรกำนัล/บัตรของขวัญ ไม่ถูกต้อง...");
                txtGiftNo.setText("");
                txtGiftNo.requestFocus();
            }
        }

        showDataToGrid();
    }

    public void getValidVoucher(String giftBarcode) {
        String giftType = giftBarcode.substring(0, 2);
        String giftPrice = giftBarcode.substring(2, 5);
        String giftModel = giftBarcode.substring(5, 8);
        String giftLot = giftBarcode.substring(8, 13);
        String giftExp = giftBarcode.substring(13, 19);
        String yy = giftExp.substring(0, 2);
        String mm = giftExp.substring(2, 4);
        String dd = giftExp.substring(4, 6);
        String giftExp2 = dd + "-" + mm + "-" + yy;
        String giftCode = giftBarcode.substring(0, 19);
        String giftNo;
        if (giftBarcode.length() == 26) {
            giftNo = giftBarcode.substring(19, 26);
        } else {
            giftNo = "";
        }
        if (giftBarcode.length() == 26) {
            if (PublicVar.Branch_GiftStatusChk.equals("Y")) {
                if (findGiftStatus(giftCode, giftNo)) {
                    if (findGiftPrice(giftPrice)) {
                        if (!giftExp.equals("000000")) {
                            if (checkExpDate(giftExp, giftExp2)) {
                                /**
                                 * * OPEN CONNECTION **
                                 */
                                MySQLConnect mysql = new MySQLConnect();
                                mysql.open();
                                try {
                                    String sql = "insert into tempgift (macno,giftbarcode,gifttype,giftprice,giftmodel,giftlot,giftexp,giftcode,giftno,giftamt) "
                                            + "values (?,?,?,?,?,?,?,?,?,?)";
                                    PreparedStatement prm11 = mysql.getConnection().prepareStatement(sql);
                                    prm11.setString(1, Value.MACNO);
                                    prm11.setString(2, giftBarcode);
                                    prm11.setString(3, giftType);
                                    prm11.setString(4, giftPrice);
                                    prm11.setString(5, giftModel);
                                    prm11.setString(6, giftLot);
                                    prm11.setString(7, giftExp2);
                                    prm11.setString(8, giftCode);
                                    prm11.setString(9, giftNo);
                                    prm11.setDouble(10, giftAmt);
                                    prm11.executeUpdate();
                                } catch (SQLException e) {
                                    MSG.ERR(e.getMessage());
                                    AppLogUtil.log(Giftvoucher.class, "error", e.getMessage());
                                } finally {
                                    mysql.close();
                                }
                            }
                        } else {
                            /**
                             * * OPEN CONNECTION **
                             */
                            MySQLConnect mysql = new MySQLConnect();
                            mysql.open();
                            try {
                                String sql = "insert into tempgift (macno,giftbarcode,gifttype,giftprice,giftmodel,giftlot,giftexp,giftcode,giftno,giftamt) "
                                        + "values (?,?,?,?,?,?,?,?,?,?)";
                                PreparedStatement prm11 = mysql.getConnection().prepareStatement(sql);
                                prm11.setString(1, Value.MACNO);
                                prm11.setString(2, giftBarcode);
                                prm11.setString(3, giftType);
                                prm11.setString(4, giftPrice);
                                prm11.setString(5, giftModel);
                                prm11.setString(6, giftLot);
                                prm11.setString(7, giftExp2);
                                prm11.setString(8, giftCode);
                                prm11.setString(9, giftNo);
                                prm11.setDouble(10, giftAmt);

                                prm11.executeUpdate();
                            } catch (SQLException e) {
                                MSG.ERR(e.getMessage());
                                AppLogUtil.log(Giftvoucher.class, "error", e.getMessage());
                            } finally {
                                mysql.close();
                            }
                        }
                    }
                }
            }
        } else {
            if (findGiftPrice(giftPrice)) {
                if (!giftExp.equals("000000")) {
                    if (checkExpDate(giftExp, giftExp2)) {
                        /**
                         * * OPEN CONNECTION **
                         */
                        MySQLConnect mysql = new MySQLConnect();
                        mysql.open();
                        try {
                            String sql = "insert into tempgift (macno,giftbarcode,gifttype,giftprice,giftmodel,giftlot,giftexp,giftcode,giftno,giftamt) "
                                    + "values (?,?,?,?,?,?,?,?,?,?)";
                            PreparedStatement prm11 = mysql.getConnection().prepareStatement(sql);
                            prm11.setString(1, Value.MACNO);
                            prm11.setString(2, giftBarcode);
                            prm11.setString(3, giftType);
                            prm11.setString(4, giftPrice);
                            prm11.setString(5, giftModel);
                            prm11.setString(6, giftLot);
                            prm11.setString(7, giftExp2);
                            prm11.setString(8, giftCode);
                            prm11.setString(9, giftNo);
                            prm11.setDouble(10, giftAmt);

                            prm11.executeUpdate();
                        } catch (SQLException e) {
                            MSG.ERR(e.getMessage());
                            AppLogUtil.log(Giftvoucher.class, "error", e.getMessage());
                        } finally {
                            mysql.close();
                        }
                    }
                } else {
                    /**
                     * * OPEN CONNECTION **
                     */
                    MySQLConnect mysql = new MySQLConnect();
                    mysql.open();
                    try {
                        String sql = "insert into tempgift (macno,giftbarcode,gifttype,giftprice,giftmodel,giftlot,giftexp,giftcode,giftno,giftamt) "
                                + "values (?,?,?,?,?,?,?,?,?,?)";
                        PreparedStatement prm11 = mysql.getConnection().prepareStatement(sql);
                        prm11.setString(1, Value.MACNO);
                        prm11.setString(2, giftBarcode);
                        prm11.setString(3, giftType);
                        prm11.setString(4, giftPrice);
                        prm11.setString(5, giftModel);
                        prm11.setString(6, giftLot);
                        prm11.setString(7, giftExp2);
                        prm11.setString(8, giftCode);
                        prm11.setString(9, giftNo);
                        prm11.setDouble(10, giftAmt);

                        prm11.executeUpdate();
                    } catch (SQLException e) {
                        MSG.ERR(e.getMessage());
                        AppLogUtil.log(Giftvoucher.class, "error", e.getMessage());
                    } finally {
                        mysql.close();
                    }
                }
            }
        }

    }

    public boolean findGiftStatus(String giftCode, String giftNo) {
        boolean isValid = false;
        /**
         * * OPEN CONNECTION **
         */
        MySQLConnect mysql = new MySQLConnect();
        mysql.open();
        try {
            Statement stmt = mysql.getConnection().createStatement();
            String sql = "select *from giftstatus where (gcode='" + giftCode + "') and (gno= '" + giftNo + "') ";
            ResultSet rs = stmt.executeQuery(sql);
            if (rs.next()) {
                isValid = true;
            } else {
                MSG.ERR("บัตรของขวัญนี้ยังไม่มีการลงทะเบียบจากสำนักงานใหญ่...ไม่สามารถนำมาใช้บริการได้...");
                isValid = false;
            }

            rs.close();
            stmt.close();
        } catch (SQLException e) {
            MSG.ERR(e.getMessage());
            AppLogUtil.log(Giftvoucher.class, "error", e.getMessage());
        } finally {
            mysql.close();
        }

        return isValid;
    }

    public Boolean findGiftPrice(String GiftPrice) {
        Boolean isValid = false;
        /**
         * * OPEN CONNECTION **
         */
        MySQLConnect mysql = new MySQLConnect();
        mysql.open();
        try {
            Statement stmt = mysql.getConnection().createStatement();
            ResultSet rs = stmt.executeQuery("select * from giftprice where (pricecode='" + GiftPrice + "')");
            if (rs.next()) {
                giftAmt = rs.getDouble("priceamt");
                isValid = true;
            } else {
                MSG.ERR("รหัสราคาบัตรกำนัล/บัตรของขัวญ ไม่ถูกต้อง...");
                giftAmt = 0.0;
                isValid = false;
            }
            rs.close();
            stmt.close();
        } catch (SQLException e) {
            MSG.ERR(e.getMessage());
            AppLogUtil.log(Giftvoucher.class, "error", e.getMessage());
        } finally {
            mysql.close();
        }

        return isValid;
    }

    public boolean checkExpDate(String giftExp, String giftExp2) {
        SimpleDateFormat dateCheck = new SimpleDateFormat("yyMMdd", Locale.ENGLISH);
        String curDate = dateCheck.format(new Date());//"091201" ;
        if (curDate.compareTo(giftExp) > 0) {
            MSG.ERR(this, "บัตรหมดอายุการใช่งานแล้วตั้งแต่วันที่ " + giftExp2);
            return false;
        } else {
            return true;
        }
    }

    public void showDataToGrid() {
        clearGrid();
        int lineCount = 1;
        /**
         * * OPEN CONNECTION **
         */
        MySQLConnect mysql = new MySQLConnect();
        mysql.open();
        try {
            Statement stmt = mysql.getConnection().createStatement();
            String LoadTempGift = "select * from tempgift where macno='" + Value.MACNO + "'";
            ResultSet rs = stmt.executeQuery(LoadTempGift);
            if (rs.next()) {
                Object[] input = {
                    rs.getString("gifttype"),
                    rs.getString("giftmodel"),
                    rs.getString("giftlot"),
                    rs.getString("giftexp"),
                    rs.getString("giftbarcode"),
                    rs.getString("giftno"),
                    rs.getDouble("giftamt")
                };
                model.addRow(input);
                lineCount++;
                
                showCell(0, 0);
            }

            rs.close();
            stmt.close();
        } catch (SQLException e) {
            MSG.ERR(e.getMessage());
            AppLogUtil.log(Giftvoucher.class, "error", e.getMessage());
        } finally {
            mysql.close();
        }

    }

    public void showCell(int row, int column) {
        if (row > 0) {
            Rectangle rect = tblShow.getCellRect(row, column, true);
            tblShow.scrollRectToVisible(rect);
            tblShow.clearSelection();
            tblShow.setRowSelectionInterval(row, row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntClearAll;
    private javax.swing.JButton bntOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblShow;
    private javax.swing.JTextField txtGiftNo;
    // End of variables declaration//GEN-END:variables
}
